GET http://localhost:8000/
###

POST http://localhost:8000/login
Content-Type: application/json

{
    "username": "leonardo",
    "password": 12345,
    "id": 4000
}

###

POST http://localhost:8000/signup
Content-Type: application/json

{
    "username": "leonardo",
    "password": 12345,
    "id": 4000
}

###

GET http://localhost:8000/notes

###
POST http://localhost:8000/notes
Content-Type: application/json

{
    "title": "texssstaaao2",
    "message": "aksjsafçdflaksfjsdllasdjflaskdf"
}