GET http://localhost:8000/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGVvbmFyZG8iLCJpYXQiOjE2Mzg2NjA1MjV9.1-jLY2M0LQG8GuBv3rH9jIVvLL_9ra69ksrmCSNSo3I

###

POST http://localhost:8000/login
Content-Type: application/json

{
    "username": "leonardo",
    "password": 12345,
    "id": 4000
}

###

POST http://localhost:8000/signup
Content-Type: application/json

{
    "username": "leonardo",
    "password": 12345,
    "id": 4000
}

###

POST http://localhost:8000/notes
Content-Type: application/json

{
    "title": "meu terceiro texto",
    "message": "aksjflaksfjsdl lasdjflaskdf",
    "idUser": 1
}